version: '3.8'

services:
  api:
    build:
      context: ./serving
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - app_network

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "8501:8501"
    networks:
      - app_network
    depends_on:
      - api

  reporting:
    build:
      context: ./reporting
      dockerfile: Dockerfile
    container_name: reporting
    volumes:
      - ./data:/app/data  # Ensure the data folder is shared with the container
    ports:
      - "8082:8082"  # Expose the Evidently UI port
    networks:
      - app_network

networks:
  app_network:
    driver: bridge